name: Publish

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
      - run: npx @anthropic-ai/mcpb pack
      - uses: softprops/action-gh-release@v2
        with:
          files: ./*.mcpb
